name       : qt5-virtualkeyboard
version    : 5.12.2
release    : 11
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.2/submodules/qtvirtualkeyboard-everywhere-src-5.12.2.tar.xz : 7111de5c78f8a0d29394409727647b90ae5906fd5105c843af98c3ae3804248d
license    : GPL-3.0
component  : desktop.qt
summary    : Qt Virtual Keyboard
description: |
    Qt Virtual Keyboard is a virtual keyboard framework that consists of a C++ backend supporting custom input methods as well as a UI frontend implemented in QML.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(xcb-xfixes)
rundeps    :
    - qt5-multimedia
setup      : |
    %qmake CONFIG+=release qtvirtualkeyboard.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
