name       : qt5-virtualkeyboard
version    : 5.12.3
release    : 12
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.3/submodules/qtvirtualkeyboard-everywhere-src-5.12.3.tar.xz : 7b83af4527310de4ab81146622f3a46677daabf05556d0e33a2e25ca2aa13b22
license    : GPL-3.0
component  : desktop.qt
summary    : Qt Virtual Keyboard
description: |
    Qt Virtual Keyboard is a virtual keyboard framework that consists of a C++ backend supporting custom input methods as well as a UI frontend implemented in QML.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(xcb-xfixes)
rundeps    :
    - qt5-multimedia
setup      : |
    %qmake CONFIG+=release qtvirtualkeyboard.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
