name       : qt5-virtualkeyboard
version    : 5.15.9
release    : 27
source     :
    - git|https://invent.kde.org/qt/qt/qtvirtualkeyboard.git : 4191fd9098ae25ffd5917370427460842e73f0cb
homepage   : https://www.qt.io
license    : GPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt Virtual Keyboard
description: |
    Qt Virtual Keyboard is a virtual keyboard framework that consists of a C++ backend supporting custom input methods as well as a UI frontend implemented in QML.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(xcb-xfixes)
rundeps    :
    - qt5-multimedia
setup      : |
    %qmake CONFIG+=release qtvirtualkeyboard.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
