name       : qt5-virtualkeyboard
version    : 5.15.3
release    : 22
source     :
    - git|https://invent.kde.org/qt/qt/qtvirtualkeyboard.git : 353b75b2e34bdae901625bbddf5c5e3f3e6c0de5
homepage   : https://www.qt.io
license    : GPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt Virtual Keyboard
description: |
    Qt Virtual Keyboard is a virtual keyboard framework that consists of a C++ backend supporting custom input methods as well as a UI frontend implemented in QML.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(xcb-xfixes)
rundeps    :
    - qt5-multimedia
setup      : |
    %qmake CONFIG+=release qtvirtualkeyboard.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
